### PR TITLE
Add test for converting CheeseFork test dates.

### PR DESCRIPTION
**Pull request by chaosite**
This should fail.

### CODE REVIEW

**Comment by lutzky** [comment]
From the build log:

```
AssertionError: expected { day: 2, month: 2, year: 2020 } to equal { day: 2, month: 2, year: 2020 }
```

...wat?

**Comment by chaosite** [comment]
OK, it seems like two things are true:

1. I still haven't grasped JavaScript equality
1. This function is actually fine, and the bug is somewhere else.

Help?

**Comment by chaosite** [comment]
OK, maybe here? https://github.com/lutzky/ttime3/blob/da9a27bf190a9412adc17ab01ad09498a61aef1d/src/formatting.ts#L16

Because it's actually `Date(year, monthIndex, day)`, and `monthIndex` is zero-based (0 is January).
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by chaosite** [comment]
But that doesn't explain where the 1 for the day came from. It's not the default value, because other test dates have `day != 1`...

**Comment by lutzky** [comment]
Ah, apparently chai's `equal` method does straight `===` comparison; deep comparison is done using `eql` instead.

**Comment by lutzky** [comment]
Alternative, `expect(something).to.deep.equal(somethingElse)`.

**Comment by lutzky** [comment]
So indeed, the problem here isn't with the cheesefork parsing, it's with the rendering. Fixing.

**Comment by chaosite** [comment]
This is no longer relevant.

**Pull request closed without merging**
